Repository codestates-seb/seb40_main_021, pull requests merged in 2022-11, with the labels that each got.

#5 [FE] Header, Gnb 레이아웃 작업
  client/src/App.js
  client/src/assets/font.css
  client/src/assets/img/bell_icon.png
  client/src/assets/img/icon_QR.png
  client/src/assets/img/icon_close.png
  client/src/assets/img/icon_close_white.png
  client/src/assets/img/icon_list.png
  client/src/assets/img/icon_menu.png
  client/src/assets/img/icon_plus.png
  client/src/assets/img/icon_signout.png
  client/src/assets/img/icon_table.png
  client/src/assets/img/logo.png
  client/src/assets/img/user_ex_img.png
  client/src/components/common/Gnb.js
  client/src/components/common/Gnb.style.js
  client/src/components/common/GnbLayout.js
  client/src/components/common/Header.js
  client/src/components/common/Header.style.js
  client/src/index.css
Labels: 스타일링

#6 [FE] Input 컴포넌트 작업
  client/src/components/Input.js
Labels: 스타일링

#11 [FE] SignupTos 디자인 구현 완료
  client/public/images/complete.png
  client/public/images/imgReg.png
  client/public/images/notes.png
  client/public/images/search.png
  client/src/components/Input.js
  client/src/pages/SignupTos/SignupTos.Style.js
  client/src/pages/SignupTos/SignupTos.js
Labels: 스타일링

#13 Fe store page
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/AdminComponents/Button.js
  client/src/components/AdminComponents/QrTable/CreateQR.js
  client/src/components/AdminComponents/QrTable/InputTable.js
  client/src/components/AdminComponents/QrTable/QrInfo.js
  client/src/components/AdminComponents/QrTable/QrList.js
  client/src/components/AdminComponents/StoreAlarm/CallAlarms.js
  client/src/components/AdminComponents/StoreAlarm/OderAlarmStyle.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlarms.js
  client/src/components/AdminComponents/StoreInfo/Buttons.js
  client/src/components/AdminComponents/StoreInfo/InfoTable.js
  client/src/components/AdminComponents/StoreInfo/InfoUpdateInput.js
  client/src/components/AdminComponents/StoreInfo/StoreInfo.js
  client/src/components/AdminComponents/TableStatus/TableList.js
  client/src/components/AdminComponents/TableStatus/TableStatus.js
  client/src/components/Input.js
  client/src/components/common/GnbLayout.js
  client/src/index.js
  client/src/pages/user/Alarm.js
  client/src/pages/user/QrTable.js
  client/src/pages/user/Store.js
  client/src/pages/user/Table.js
  client/src/redux/.js
  client/src/redux/action/action.js
  client/src/redux/reducers/adminReducer.js
  client/src/redux/store/store.js
Labels: 기능

#15 [FE] 사용자 페이지 기능 구현
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlarms.js
  client/src/components/menu/BottomNav.js
  client/src/components/menu/CartItem.js
  client/src/components/menu/Header.js
  client/src/components/menu/Menu.js
  client/src/components/menu/MenuDetailed.js
  client/src/components/menu/MenuList.js
  client/src/components/menu/Modal.js
  client/src/components/menu/OrderNav.js
  client/src/components/menu/OrderedItem.js
  client/src/index.css
  client/src/index.js
  client/src/pages/menu/Cart.js
  client/src/pages/menu/Home.js
  client/src/pages/menu/Order.js
  client/src/pages/menu/OrderedList.js
  client/src/pages/menu/Store.js
  client/src/redux/.js
  client/src/redux/actions/menuAction.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/menuReducer.js
  client/src/redux/store/index.js
  client/src/reportWebVitals.js
  client/src/setupTests.js
  client/src/style/.js
  client/src/style/menu.style.js
Labels: 버그, 기능, 리팩토링, 스타일링

#24 [FE] 상태관리 및 UI 수정
  client/public/favicon.ico
  client/public/index.html
  client/public/logo192.png
  client/public/logo512.png
  client/public/manifest.json
  client/public/robots.txt
  client/src/components/menu/BottomNav.js
  client/src/components/menu/CartItem.js
  client/src/components/menu/Category.js
  client/src/components/menu/NavMenu.js
  client/src/index.css
  client/src/pages/menu/Home.js
  client/src/redux/actions/menuAction.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/rootReducer.js
  client/src/style/menu.style.js
Labels: 기능, 리팩토링, 스타일링

#25 QR생성/확인 페이지 작성
  client/src/App.js
  client/src/components/AdminComponents/Button.js
  client/src/components/AdminComponents/QrTable/Button.js
  client/src/components/AdminComponents/QrTable/QrInfo.js
  client/src/components/AdminComponents/QrTable/QrList.js
  client/src/components/AdminComponents/QrTable/QrTable.js
  client/src/components/AdminComponents/StoreAlarm/OderAlarmStyle.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlram.js
  client/src/components/AdminComponents/StoreInfo/Buttons.js
  client/src/components/AdminComponents/StoreInfo/InfoTable.js
  client/src/components/AdminComponents/StoreInfo/StoreInfo.js
  client/src/components/AdminComponents/TableStatus/TableList.js
  client/src/components/AdminComponents/TableStatus/TableStatus.js
  client/src/components/AdminComponents/createTable/Button.js
  client/src/components/AdminComponents/createTable/CreateTable.js
  client/src/components/AdminComponents/createTable/InputTable.js
  client/src/components/AdminComponents/createTable/QrInfo.js
  client/src/components/AdminComponents/createTable/QrList.js
  client/src/pages/user/AlarmsPage.js
  client/src/pages/user/CreateTablePage.js
  client/src/pages/user/QrTablePage.js
  client/src/pages/user/StorePage.js
  client/src/pages/user/TablePage.js
  client/src/redux/action/action.js
  client/src/redux/reducers/adminReducer.js
Labels: 기능, 스타일링

#26 [FE] login 유효성 검사
  client/src/pages/Signup/Login.Style.js
  client/src/pages/Signup/Login.js
Labels: 기능, 스타일링

#27 [FE] SignupTos 디자인 수정, 클릭 이벤트 추가
  client/src/pages/Signup/SignupTos.Style.js
  client/src/pages/Signup/SignupTos.js
Labels: 기능, 스타일링

#31 adminReducer 에러 수정 및 QR Print 화면 개선
  client/src/App.js
  client/src/components/AdminComponents/Print/Printe.js
  client/src/components/AdminComponents/Print/Qrimg.js
  client/src/components/AdminComponents/QrTable/Button.js
  client/src/components/AdminComponents/QrTable/QrInfo.js
  client/src/components/AdminComponents/QrTable/QrList.js
  client/src/components/AdminComponents/QrTable/QrTable.js
  client/src/components/AdminComponents/StoreInfo/Buttons.js
  client/src/components/AdminComponents/StoreInfo/StoreInfo.js
  client/src/components/AdminComponents/createTable/Button.js
  client/src/components/AdminComponents/createTable/CreateTable.js
  client/src/components/AdminComponents/createTable/QrInfo.js
  client/src/components/AdminComponents/createTable/QrList.js
  client/src/index.js
  client/src/pages/user/QrTablePage.js
  client/src/redux/action/action.js
  client/src/redux/reducers/adminReducer.js
  client/src/redux/store/index.js
Labels: bug, 기능

#34 [FE] fe-userLayout => fe
  client/src/App.js
  client/src/components/Input.js
  client/src/components/Menu/ButtonWrap.js
  client/src/components/Menu/Category/CategoryAdd.js
  client/src/components/Menu/Category/CategoryLi.js
  client/src/components/Menu/Category/CategoryLi.style.js
  client/src/components/Menu/MenuList.js
  client/src/components/common/Gnb.js
  client/src/components/common/Gnb.style.js
  client/src/components/common/GnbLayout.js
  client/src/pages/menu/Menu.js
  client/src/pages/menu/SetMenu.js
  client/src/pages/menu/SetMenu.style.js
  client/src/redux/action/action.js
  client/src/redux/reducers/categoryUserItemReducer.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/menuUserItemReducer.js
Labels: 기능, 리팩토링, 설정

#36 [FE] MemberInfo 유효성, 오픈 API 연동 완료
  client/package-lock.json
  client/package.json
  client/src/pages/Signup/MemberInfo.Style.js
  client/src/pages/Signup/MemberInfo.js
Labels: 기능

#37 [FE] StoreInfo 오픈 api 연동 완료, 유효성 검사 완료
  client/package-lock.json
  client/package.json
  client/src/components/Menu/MenuImg.js
  client/src/components/PostCode/Postcode.js
  client/src/pages/Signup/StoreInfo.Style.js
  client/src/pages/Signup/StoreInfo.js
Labels: 기능

#41 [FE] 통신테스트 완료
  client/.eslintrc.json
  client/.prettierrc.json
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/menu/AnimatedRoutes.js
  client/src/components/menu/BottomNav.js
  client/src/components/menu/CartItem.js
  client/src/components/menu/Category.js
  client/src/components/menu/Header.js
  client/src/components/menu/Menu.js
  client/src/components/menu/MenuDetailed.js
  client/src/components/menu/MenuList.js
  client/src/components/menu/Modal.js
  client/src/components/menu/NavMenu.js
  client/src/components/menu/OrderedItem.js
  client/src/components/menu/Search.js
  client/src/components/menu/StoreInfo.js
  client/src/index.css
  client/src/pages/menu/Cart.js
  client/src/pages/menu/Home.js
  client/src/pages/menu/Order.js
  client/src/pages/menu/OrderedList.js
  client/src/pages/menu/Store.js
  client/src/pages/user/index.js
  client/src/redux/actions/menuAction.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/menuReducer.js
  client/src/redux/reducers/rootReducer.js
  client/src/redux/reducers/stateReducer.js
  client/src/setupProxy.js
  client/src/style/menu.style.js
  client/src/util/.js
Labels: 기능, 리팩토링

#47 [FE] 브랜치 합병
  client/.prettierrc.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/AdminComponents/Print/Printe.js
  client/src/components/AdminComponents/Print/Qrimg.js
  client/src/components/AdminComponents/QrTable/QrInfo.js
  client/src/components/AdminComponents/QrTable/QrList.js
  client/src/components/AdminComponents/QrTable/QrTable.js
  client/src/components/AdminComponents/StoreAlarm/CallAlarm.js
  client/src/components/AdminComponents/StoreAlarm/CallAlarms.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlarms.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlram.js
  client/src/components/AdminComponents/TableStatus/TableList.js
  client/src/components/AdminComponents/TableStatus/TableStatus.js
  client/src/components/AdminComponents/createTable/Button.js
  client/src/components/AdminComponents/createTable/CreateTable.js
  client/src/components/AdminComponents/createTable/InputTable.js
  client/src/components/AdminComponents/createTable/QrInfo.js
  client/src/components/Menu/Category/CategoryLi.style.js
  client/src/components/menu/CartItem.js
  client/src/components/menu/Category.js
  client/src/components/menu/Header.js
  client/src/components/menu/Menu.js
  client/src/components/menu/MenuDetailed.js
  client/src/components/menu/Modal.js
  client/src/components/menu/Search.js
  client/src/components/menu/StoreInfo.js
  client/src/components/usermenu/AnimatedRoutes.js
  client/src/components/usermenu/BottomNav.js
  client/src/components/usermenu/CartItem.js
  client/src/components/usermenu/Category.js
  client/src/components/usermenu/Header.js
  client/src/components/usermenu/Menu.js
  client/src/components/usermenu/MenuDetailed.js
  client/src/components/usermenu/Modal.js
  client/src/components/usermenu/NavMenu.js
  client/src/components/usermenu/OrderNav.js
  client/src/components/usermenu/OrderedItem.js
  client/src/components/usermenu/Search.js
  client/src/components/usermenu/StoreInfo.js
  client/src/components/usermenu/StoreMenuList.js
  client/src/menuApp.js
  client/src/pages/Signup/Complete.js
  client/src/pages/Signup/Login.js
  client/src/pages/Signup/SignupTos.js
  client/src/pages/menu/Cart.js
  client/src/pages/menu/Home.js
  client/src/pages/menu/Order.js
  client/src/pages/menu/OrderedList.js
  client/src/pages/menu/Store.js
  client/src/pages/user/TablePage.js
  client/src/redux/action/action.js
  client/src/redux/reducers/adminReducer.js
  client/src/redux/reducers/stateReducer.js
  client/src/setupProxy.js
  client/src/style/menu.style.js
  client/src/util/useAxios.js
  client/src/util/useInterval.js
Labels: 리팩토링

#48 [FE] 메뉴 등록, 확인페이지 통신
  client/.prettierrc.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Menu/Category/CategoryAdd.js
  client/src/components/Menu/Category/CategoryLi.js
  client/src/components/Menu/Category/categoryData.js
  client/src/components/Menu/MenuList.js
  client/src/components/Menu/MenuViewList.js
  client/src/pages/menu/Menu.js
  client/src/pages/menu/Order.js
  client/src/pages/menuAdmin/CategoryMapLi.js
  client/src/pages/menuAdmin/Menu.js
  client/src/pages/menuAdmin/MenuLi.js
  client/src/pages/menuAdmin/SetMenu.js
  client/src/pages/menuAdmin/SetMenu.style.js
  client/src/pages/menuAdmin/SetMenuLi.js
  client/src/redux/action/action.js
  client/src/redux/reducers/categoryUserItemReducer.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/menuSaveItemReducer.js
  client/src/redux/reducers/menuUserItemReducer.js
  client/src/util/useAxios.js
Labels: 버그, 기능

#50 [FE] 회원가입, 로그인 프록시 통신 테스트 완료
  client/src/assets/img/bottomArrow.png
  client/src/assets/img/search.png
  client/src/assets/img/topArrow.png
  client/src/components/PostCode/Postcode.js
  client/src/pages/Signup/Complete.Style.js
  client/src/pages/Signup/Complete.js
  client/src/pages/Signup/Login.Style.js
  client/src/pages/Signup/Login.js
  client/src/pages/Signup/MemberInfo.Style.js
  client/src/pages/Signup/MemberInfo.js
  client/src/pages/Signup/SignupTos.Style.js
  client/src/pages/Signup/SignupTos.js
  client/src/pages/Signup/StoreInfo.Style.js
  client/src/pages/Signup/StoreInfo.js
  client/src/redux/action/action.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/userMemberReducer.js
Labels: 버그, 기능, 스타일링

#51 [FE] 라우터 path 파라미터 설정완료
  client/src/App.js
  client/src/components/usermenu/AnimatedRoutes.js
  client/src/components/usermenu/BottomNav.js
  client/src/components/usermenu/Category.js
  client/src/components/usermenu/Header.js
  client/src/components/usermenu/MenuDetailed.js
  client/src/components/usermenu/Modal.js
  client/src/components/usermenu/NavMenu.js
  client/src/components/usermenu/OrderNav.js
  client/src/components/usermenu/Search.js
  client/src/pages/menu/Cart.js
  client/src/pages/menu/OrderedList.js
  client/src/pages/menu/Store.js
Labels: 기능

#55 qr 생성 ,수정 유효성 검사 추가
  client/src/components/AdminComponents/QrTable/QrInfo.js
  client/src/components/AdminComponents/QrTable/QrTable.js
  client/src/components/AdminComponents/StoreAlarm/CallAlarms.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlarms.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlram.js
  client/src/components/AdminComponents/TableStatus/TableList.js
  client/src/components/AdminComponents/createTable/Button.js
  client/src/components/AdminComponents/createTable/InputTable.js
  client/src/components/AdminComponents/createTable/QrInfo.js
  client/src/redux/reducers/adminReducer.js
Labels: 기능

#56 [FE] 전반적인 페이지 UI 수정
  client/src/components/AdminComponents/QrTable/QrInfo.js
  client/src/components/AdminComponents/QrTable/QrList.js
  client/src/components/AdminComponents/QrTable/QrTable.js
  client/src/components/AdminComponents/StoreAlarm/CallAlarm.js
  client/src/components/AdminComponents/StoreAlarm/CallAlarms.js
  client/src/components/AdminComponents/StoreAlarm/OderAlarmStyle.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlarms.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlram.js
  client/src/components/AdminComponents/StoreInfo/Buttons.js
  client/src/components/AdminComponents/StoreInfo/StoreInfo.js
  client/src/components/AdminComponents/TableStatus/TableList.js
  client/src/components/AdminComponents/TableStatus/TableStatus.js
  client/src/components/AdminComponents/createTable/CreateTable.js
  client/src/components/AdminComponents/createTable/InputTable.js
  client/src/components/AdminComponents/createTable/QrInfo.js
  client/src/components/AdminComponents/createTable/QrList.js
  client/src/components/Input.js
  client/src/components/Menu/ButtonWrap.js
  client/src/components/Menu/Category/CategoryLi.style.js
  client/src/components/Menu/MenuList.js
  client/src/components/Menu/MenuList.style.js
  client/src/components/common/Gnb.js
  client/src/components/common/Gnb.style.js
  client/src/components/common/GnbLayout.js
  client/src/components/common/Header.js
  client/src/components/common/Header.style.js
  client/src/index.css
  client/src/pages/Signup/Complete.Style.js
  client/src/pages/Signup/Complete.js
  client/src/pages/Signup/Login.Style.js
  client/src/pages/Signup/Login.js
  client/src/pages/Signup/MemberInfo.Style.js
  client/src/pages/Signup/MemberInfo.js
  client/src/pages/Signup/SignupTos.Style.js
  client/src/pages/Signup/SignupTos.js
  client/src/pages/Signup/StoreInfo.Style.js
  client/src/pages/Signup/StoreInfo.js
  client/src/pages/menuAdmin/SetMenu.js
  client/src/pages/menuAdmin/SetMenu.style.js
  client/src/pages/user/AlarmsPage.js
  client/src/pages/user/CreateTablePage.js
  client/src/pages/user/QrTablePage.js
  client/src/pages/user/StorePage.js
  client/src/pages/user/TablePage.js
  client/src/setupProxy.js
  client/src/util/useAxios.js
Labels: 스타일링

#58 [FE] StorePage 인풋창 더미데이터 연결, 유효성 검사
  client/src/components/AdminComponents/StoreInfo/Buttons.js
  client/src/components/AdminComponents/StoreInfo/InfoUpdateInput.js
  client/src/components/AdminComponents/StoreInfo/StoreInfo.js
  client/src/components/Input.js
  client/src/pages/Signup/Login.js
  client/src/pages/Signup/MemberInfo.js
  client/src/pages/Signup/StoreInfo.js
  client/src/pages/user/StorePage.js
  client/src/util/useAxios.js
Labels: 기능, 스타일링

#64 가게정보 통신(get,patch) 및 유효성 검사 작성
  client/src/components/AdminComponents/StoreAlarm/CallAlarms.js
  client/src/components/AdminComponents/StoreAlarm/OderAlarmStyle.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlarms.js
  client/src/components/AdminComponents/StoreInfo/Buttons.js
  client/src/components/AdminComponents/StoreInfo/InfoTable.js
  client/src/components/AdminComponents/StoreInfo/InfoUpdateInput.js
  client/src/components/AdminComponents/StoreInfo/StoreInfo.js
  client/src/components/Input.js
  client/src/pages/user/index.js
  client/src/redux/action/action.js
  client/src/redux/reducers/adminReducer.js
Labels: 기능

#65 [FE] menu 수정 error 수정완료
  client/src/components/Menu/Category/CategoryAdd.js
  client/src/components/Menu/Category/CategoryLi.js
  client/src/components/Preview/PreviewContent.js
  client/src/pages/menuAdmin/CategoryMapLi.js
  client/src/pages/menuAdmin/Menu.js
  client/src/pages/menuAdmin/SetMenu.js
  client/src/pages/menuAdmin/SetMenu.style.js
  client/src/redux/action/action.js
  client/src/setupProxy.js
Labels: 버그, 리팩토링, 설정

#66 css 수정 및 gnb 알람 기능 추가
  client/src/components/AdminComponents/QrTable/QrTable.js
  client/src/components/AdminComponents/StoreAlarm/CallAlarms.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlarms.js
  client/src/components/AdminComponents/StoreInfo/Buttons.js
  client/src/components/AdminComponents/StoreInfo/StoreInfo.js
  client/src/components/AdminComponents/createTable/CreateTable.js
  client/src/components/AdminComponents/createTable/InputTable.js
  client/src/components/AdminComponents/createTable/QrInfo.js
  client/src/components/AdminComponents/createTable/QrList.js
  client/src/components/common/Gnb.js
  client/src/pages/user/CreateTablePage.js
  client/src/pages/user/QrTablePage.js
  client/src/pages/user/StorePage.js
  client/src/redux/action/action.js
  client/src/redux/reducers/adminReducer.js
Labels: 기능

#67 [FE] error 스타일 변경
  client/src/pages/menuAdmin/CategoryMapLi.js
  client/src/pages/menuAdmin/Menu.js
Labels: 버그, 스타일링

#69 [FE] signup 통신, 유저아이디, 디자인 수정
  client/src/pages/Signup/Login.js
  client/src/pages/Signup/MemberInfo.Style.js
  client/src/pages/Signup/MemberInfo.js
  client/src/pages/Signup/StoreInfo.js
Labels: 기능, 스타일링

#74 [FE] menu 등록 설정, mobile style 수정, preview 설정
  client/src/components/AdminComponents/StoreInfo/Buttons.js
  client/src/components/AdminComponents/StoreInfo/StoreInfo.js
  client/src/components/Menu/ButtonWrap.js
  client/src/components/Menu/MenuList.js
  client/src/components/Menu/MenuList.style.js
  client/src/components/Preview/HeaderPreview.js
  client/src/components/Preview/HomePreview.js
  client/src/components/Preview/NavMenuPreview.js
  client/src/components/Preview/PreviewContent.js
  client/src/components/Preview/PreviewModal.js
  client/src/components/Preview/StorePreview.js
  client/src/components/Preview/menuAppPreview.js
  client/src/pages/menuAdmin/Menu.js
  client/src/pages/menuAdmin/SetMenu.js
  client/src/pages/menuAdmin/SetMenu.style.js
  client/src/pages/menuAdmin/SetMenuLi.js
  client/src/redux/reducers/menuUserItemReducer.js
  client/src/setupProxy.js
  client/src/style/menu.style.js
Labels: 기능, 스타일링

#75 [FE] signup 유효성 검사 추가 수정 완료
  client/src/App.js
  client/src/pages/Signup/Complete.Style.js
  client/src/pages/Signup/Login.Style.js
  client/src/pages/Signup/Login.js
  client/src/pages/Signup/MemberInfo.Style.js
  client/src/pages/Signup/MemberInfo.js
  client/src/pages/Signup/SignupTos.Style.js
  client/src/pages/Signup/StoreInfo.Style.js
  client/src/pages/Signup/StoreInfo.js
Labels: 기능, 스타일링

#76 [FE} 메인 서비스 페이지 UI 1차완료
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/assets/image/adminPage.svg
  client/src/assets/image/qr.svg
  client/src/assets/image/qrorderbg.svg
  client/src/assets/image/service-icon1.svg
  client/src/assets/image/service-icon2.svg
  client/src/assets/image/service-icon3.svg
  client/src/assets/image/usermenu.svg
  client/src/components/Menu/MenuList.js
  client/src/components/home/Footer.js
  client/src/components/home/Section1.js
  client/src/components/home/Section2.js
  client/src/components/home/Section3.js
  client/src/components/home/Slider.js
  client/src/components/usermenu/NavMenu.js
  client/src/pages/index.js
  client/src/redux/reducers/adminReducer.js
  client/src/setupProxy.js
  client/src/style/index.style.js
Labels: 기능, 스타일링

#78 ♻️ Refactor: proxy삭제 및 통신 domain 설정
  client/.env
  client/package-lock.json
  client/package.json
  client/src/components/AdminComponents/QrTable/QrTable.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlram.js
  client/src/components/AdminComponents/StoreInfo/Buttons.js
  client/src/components/AdminComponents/StoreInfo/StoreInfo.js
  client/src/components/AdminComponents/TableStatus/TableList.js
  client/src/components/AdminComponents/createTable/Button.js
  client/src/components/AdminComponents/createTable/InputTable.js
  client/src/components/AdminComponents/createTable/QrInfo.js
  client/src/components/Menu/Category/CategoryAdd.js
  client/src/components/Menu/Category/CategoryLi.js
  client/src/components/Menu/Category/categoryData.js
  client/src/components/Preview/NavMenuPreview.js
  client/src/components/Preview/StorePreview.js
  client/src/components/common/Gnb.js
  client/src/components/common/Header.js
  client/src/components/usermenu/BottomNav.js
  client/src/components/usermenu/Category.js
  client/src/components/usermenu/Modal.js
  client/src/components/usermenu/NavMenu.js
  client/src/components/usermenu/OrderNav.js
  client/src/components/usermenu/Search.js
  client/src/pages/Signup/Login.js
  client/src/pages/Signup/StoreInfo.js
  client/src/pages/menu/Cart.js
  client/src/pages/menu/OrderedList.js
  client/src/pages/menu/Store.js
  client/src/pages/menuAdmin/CategoryMapLi.js
  client/src/pages/menuAdmin/Menu.js
  client/src/pages/menuAdmin/MenuLi.js
  client/src/pages/menuAdmin/SetMenu.js
  client/src/pages/menuAdmin/SetMenuLi.js
  client/src/redux/actions/menuAction.js
  client/src/redux/reducers/adminReducer.js
  client/src/redux/reducers/menuReducer.js
  client/src/redux/reducers/stateReducer.js
  client/src/setupProxy.js
  client/src/util/useAxios.js
Labels: 리팩토링, 설정

#79 테이블 목록 수정 ,삭제 버그 및 css 수정
  client/src/components/AdminComponents/QrTable/QrInfo.js
  client/src/components/AdminComponents/QrTable/QrList.js
  client/src/components/AdminComponents/QrTable/QrTable.js
  client/src/components/AdminComponents/StoreAlarm/CallAlarm.js
  client/src/components/AdminComponents/StoreInfo/InfoUpdateInput.js
  client/src/components/AdminComponents/StoreInfo/StoreInfo.js
  client/src/components/AdminComponents/TableStatus/TableStatus.js
  client/src/components/AdminComponents/createTable/Button.js
  client/src/components/AdminComponents/createTable/QrInfo.js
  client/src/components/AdminComponents/createTable/QrList.js
  client/src/components/Input.js
  client/src/components/common/Gnb.js
  client/src/pages/Signup/Login.js
  client/src/pages/Signup/StoreInfo.js
  client/src/pages/user/StorePage.js
  client/src/redux/action/action.js
  client/src/redux/reducers/adminReducer.js
Labels: 버그
