Repository codestates-seb/seb40_main_021, pull requests merged in 2022-12, with the labels that each got.

#80 🐛 BUG: 알람 버그 수정
  client/src/components/AdminComponents/StoreAlarm/CallAlarm.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlarms.js
  client/src/components/AdminComponents/StoreInfo/StoreInfo.js
  client/src/components/common/Gnb.js
  client/src/components/usermenu/NavMenu.js
  client/src/pages/Signup/Login.js
Labels: 버그

#82 [FE] 메인페이지 반응형 구현 완료
  client/package.json
  client/src/components/common/Gnb.js
  client/src/components/home/Footer.js
  client/src/components/home/Section2.js
  client/src/components/home/Section3.js
  client/src/style/footer.style.js
  client/src/style/index.style.js
Labels: 스타일링

#83 [FE] signup 오류 수정
  client/package-lock.json
  client/package.json
  client/src/components/common/Header.js
  client/src/index.js
  client/src/pages/Signup/Login.Style.js
  client/src/pages/Signup/Login.js
  client/src/pages/Signup/MemberInfo.Style.js
  client/src/pages/Signup/MemberInfo.js
  client/src/pages/Signup/SignupTos.js
  client/src/pages/Signup/StoreInfo.js
  client/src/redux/action/action.js
  client/src/redux/reducers/globalTokenReducer.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/userMemberReducer.js
Labels: 버그, 기능, 스타일링

#84 [FE] 로그인 상태 리듀서 / 로그아웃 기능 완료
  client/src/App.js
  client/src/components/common/Header.js
  client/src/components/common/Header.style.js
  client/src/pages/Signup/Login.js
  client/src/pages/Signup/MemberInfo.js
  client/src/pages/Signup/SignupTos.js
  client/src/pages/Signup/StoreInfo.js
  client/src/redux/action/action.js
  client/src/redux/reducers/userMemberReducer.js
Labels: 설정

#85 [FE] menu , category 유효성 및 이미지 전송, preview 설정 완
  client/src/components/Input.js
  client/src/components/Menu/ButtonWrap.js
  client/src/components/Menu/Category/CategoryLi.js
  client/src/components/Menu/MenuList.js
  client/src/components/Menu/MenuViewList.js
  client/src/components/Preview/BottomNavPreview.js
  client/src/components/Preview/NavMenuPreview.js
  client/src/components/Preview/PreviewModal.js
  client/src/components/Preview/menuAppPreview.js
  client/src/components/usermenu/Menu.js
  client/src/pages/menuAdmin/SetMenu.js
  client/src/pages/menuAdmin/SetMenuLi.js
  client/src/redux/action/action.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/menuUserItemReducer.js
  client/src/redux/reducers/setMenuStateChangeReducer.js
Labels: 버그, 리팩토링, 설정

#87 BUG: storeInfo page 버그 수정
  client/src/components/AdminComponents/StoreAlarm/OrderAlarms.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlram.js
  client/src/components/AdminComponents/StoreInfo/Buttons.js
  client/src/components/AdminComponents/StoreInfo/InfoTable.js
  client/src/components/AdminComponents/StoreInfo/InfoUpdateInput.js
  client/src/components/AdminComponents/StoreInfo/StoreInfo.js
  client/src/components/Input.js
  client/src/components/common/Gnb.js
  client/src/pages/Signup/MemberInfo.js
  client/src/pages/Signup/SignupTos.js
  client/src/pages/Signup/StoreInfo.js
  client/src/pages/user/StorePage.js
  client/src/redux/action/action.js
Labels: bug

#88 [FE] signup 수정
  client/src/components/Menu/MenuImg.js
  client/src/pages/Signup/Login.js
  client/src/pages/Signup/MemberInfo.Style.js
  client/src/pages/Signup/MemberInfo.js
  client/src/pages/Signup/StoreInfo.js
Labels: 버그, 기능

#90 알람 버그 , qr print paging 구현 및 admin,qr print css 수정
  client/.gitignore
  client/src/assets/img/qrScanIcon.png
  client/src/components/AdminComponents/Print/Printe.js
  client/src/components/AdminComponents/Print/Qrimg.js
  client/src/components/AdminComponents/QrTable/QrInfo.js
  client/src/components/AdminComponents/QrTable/QrList.js
  client/src/components/AdminComponents/QrTable/QrTable.js
  client/src/components/AdminComponents/StoreAlarm/CallAlarms.js
  client/src/components/AdminComponents/StoreAlarm/OderAlarmStyle.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlarms.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlram.js
  client/src/components/AdminComponents/StoreInfo/Buttons.js
  client/src/components/AdminComponents/StoreInfo/InfoTable.js
  client/src/components/AdminComponents/StoreInfo/InfoUpdateInput.js
  client/src/components/AdminComponents/StoreInfo/StoreInfo.js
  client/src/components/AdminComponents/TableStatus/TableList.js
  client/src/components/AdminComponents/TableStatus/TableStatus.js
  client/src/components/AdminComponents/createTable/Button.js
  client/src/components/common/Gnb.js
  client/src/pages/user/StorePage.js
  client/src/pages/user/TablePage.js
  client/src/redux/action/action.js
  client/src/redux/reducers/adminReducer.js
Labels: 기능

#91 [FE] 테스트 후 버그사항 수정
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/assets/image/logo-white.svg
  client/src/assets/image/logo.svg
  client/src/assets/image/qrorderbg.png
  client/src/assets/image/qrorderbg.svg
  client/src/components/common/Header.js
  client/src/components/common/Header.style.js
  client/src/components/home/Footer.js
  client/src/components/home/Section1.js
  client/src/components/home/Section2.js
  client/src/components/home/Section3.js
  client/src/components/home/Slider.js
  client/src/components/usermenu/BottomNav.js
  client/src/components/usermenu/CartItem.js
  client/src/components/usermenu/Header.js
  client/src/components/usermenu/Menu.js
  client/src/components/usermenu/NavMenu.js
  client/src/components/usermenu/OrderedItem.js
  client/src/components/usermenu/Search.js
  client/src/pages/menu/Cart.js
  client/src/pages/menu/OrderedList.js
  client/src/pages/menu/Store.js
  client/src/style/footer.style.js
  client/src/style/index.style.js
  client/src/style/menu.style.js
Labels: 버그, 리팩토링, 스타일링

#92 [FE] 카테고리, gnb 수정
  client/src/components/Menu/Category/CategoryLi.js
  client/src/components/Menu/Category/categoryData.js
  client/src/components/Menu/MenuViewList.js
  client/src/components/Preview/StorePreview.js
  client/src/components/common/GnbLayout.js
  client/src/components/common/Header.js
  client/src/components/common/Header.style.js
  client/src/components/common/HeaderUser.js
  client/src/pages/Signup/MemberInfo.js
  client/src/pages/Signup/SignupTos.js
  client/src/pages/Signup/StoreInfo.js
  client/src/pages/menuAdmin/SetMenu.js
  client/src/redux/action/action.js
  client/src/redux/reducers/adminReducer.js
  client/src/redux/reducers/menuUserItemReducer.js
  client/src/style/GlobalStyle.js
Labels: 버그, 리팩토링

#93 [FE] signup 오류 수정
  client/src/assets/images/complete.png
  client/src/assets/images/imgReg.png
  client/src/assets/images/notes.png
  client/src/assets/images/search.png
  client/src/assets/img/complete.png
  client/src/assets/img/imgReg.png
  client/src/assets/img/notes.png
  client/src/pages/Signup/Complete.js
  client/src/pages/Signup/MemberInfo.js
  client/src/pages/Signup/SignupTos.js
  client/src/pages/Signup/StoreInfo.js
Labels: 버그, 기능

#94 💄 Style:qr print css 수정
  client/src/components/AdminComponents/Print/Printe.js
  client/src/components/AdminComponents/Print/Qrimg.js
Labels: 스타일링

#95 admin page scroll css 수정 및 테이블 번호 입력 안하고 테이블 추가 할때 생기는 버그 수정
  client/src/components/AdminComponents/Print/Printe.js
  client/src/components/AdminComponents/StoreAlarm/CallAlarms.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlarms.js
  client/src/components/AdminComponents/StoreInfo/StoreInfo.js
  client/src/components/AdminComponents/TableStatus/TableStatus.js
  client/src/components/AdminComponents/createTable/Button.js
  client/src/components/AdminComponents/createTable/QrList.js
Labels: 버그, 스타일링

#96 Fe 추가 수정!
  client/src/assets/image/icon_store.png
  client/src/assets/image/icon_store_white.png
  client/src/components/Menu/Category/CategoryLi.js
  client/src/components/Menu/MenuList.js
  client/src/components/Menu/MenuViewList.js
  client/src/components/common/Gnb.js
  client/src/components/common/Gnb.style.js
  client/src/components/common/GnbLayout.js
  client/src/components/common/Header.js
  client/src/components/common/HeaderUser.js
  client/src/redux/action/action.js
  client/src/redux/reducers/index.js
  client/src/redux/reducers/isLoginReducer.js
  client/src/redux/reducers/menuSaveItemReducer.js
  client/src/redux/reducers/userMemberReducer.js
Labels: 버그, 기능, 리팩토링

#97 [FE] signup 유효성 검사 수정
  client/src/pages/Signup/Complete.js
  client/src/pages/Signup/Login.js
  client/src/pages/Signup/MemberInfo.js
  client/src/pages/Signup/StoreInfo.js
Labels: 버그, 기능

#100 [FE] 이미지 코드 수정
  client/src/pages/Signup/StoreInfo.js
Labels: 버그

#101 [FE] 이미지,텍스트 추가 및 css 수정
  client/src/assets/image/QRorder.png
  client/src/assets/image/admin1.png
  client/src/assets/image/admin2.png
  client/src/assets/image/admin3.png
  client/src/assets/image/admin4.png
  client/src/assets/image/admin5.png
  client/src/assets/image/admin6.png
  client/src/assets/image/admin7.png
  client/src/assets/image/adminPage.svg
  client/src/assets/image/menu1.png
  client/src/assets/image/menu2.png
  client/src/assets/image/menu3.png
  client/src/assets/image/menu4.png
  client/src/assets/image/menu5.png
  client/src/assets/image/menu6.png
  client/src/assets/image/menu7.png
  client/src/assets/image/menu8.png
  client/src/assets/image/usermenu.svg
  client/src/components/AdminComponents/TableStatus/TableStatus.js
  client/src/components/Menu/Category/CategoryLi.js
  client/src/components/common/Header.js
  client/src/components/common/HeaderUser.js
  client/src/components/home/Section1.js
  client/src/components/home/Section3.js
  client/src/components/home/Slider.js
  client/src/components/usermenu/CartItem.js
  client/src/components/usermenu/Menu.js
  client/src/components/usermenu/MenuDetailed.js
  client/src/components/usermenu/NavMenu.js
  client/src/components/usermenu/OrderedItem.js
  client/src/pages/menu/Cart.js
  client/src/pages/menu/OrderedList.js
  client/src/style/index.style.js
  client/src/style/menu.style.js
Labels: 버그, 리팩토링, 스타일링

#103 [FE] Complete 버튼 디자인 수정
  client/src/pages/Signup/Complete.Style.js
Labels: 스타일링

#104 [FE] 이미지 상세 설정
  client/src/components/AdminComponents/Print/Printe.js
  client/src/components/AdminComponents/QrTable/QrTable.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlram.js
  client/src/components/AdminComponents/StoreInfo/Buttons.js
  client/src/components/AdminComponents/StoreInfo/InfoUpdateInput.js
  client/src/components/AdminComponents/StoreInfo/StoreInfo.js
  client/src/components/AdminComponents/createTable/Button.js
  client/src/components/AdminComponents/createTable/InputTable.js
  client/src/components/Menu/Category/CategoryLi.js
  client/src/components/Menu/MenuImg.js
  client/src/components/Menu/MenuList.js
  client/src/components/Preview/NavMenuPreview.js
  client/src/components/Preview/PreviewModal.js
  client/src/components/common/Gnb.js
  client/src/components/common/GnbLayout.js
  client/src/components/usermenu/Category.js
  client/src/components/usermenu/Modal.js
  client/src/components/usermenu/NavMenu.js
  client/src/components/usermenu/OrderNav.js
  client/src/components/usermenu/Search.js
  client/src/pages/Signup/Login.js
  client/src/pages/Signup/MemberInfo.js
  client/src/pages/Signup/StoreInfo.js
  client/src/pages/menu/Cart.js
  client/src/pages/menu/Home.js
  client/src/pages/menu/OrderedList.js
  client/src/pages/menuAdmin/SetMenu.js
  client/src/pages/user/StorePage.js
  client/src/style/menu.style.js
Labels: 버그, 리팩토링, 설정

#105 Style:가게정보 페이지 css 수정
  client/src/components/AdminComponents/QrTable/QrInfo.js
  client/src/components/AdminComponents/QrTable/QrList.js
  client/src/components/AdminComponents/QrTable/QrTable.js
  client/src/components/AdminComponents/StoreAlarm/OderAlarmStyle.js
  client/src/components/AdminComponents/StoreAlarm/OrderAlram.js
  client/src/components/AdminComponents/StoreInfo/Buttons.js
  client/src/components/AdminComponents/StoreInfo/StoreInfo.js
  client/src/components/AdminComponents/TableStatus/TableList.js
  client/src/components/AdminComponents/TableStatus/TableStatus.js
  client/src/pages/user/StorePage.js
  client/src/pages/user/TablePage.js
  client/src/redux/action/action.js
  client/src/redux/reducers/adminReducer.js
Labels: 스타일링

#106 [FE] 버그 및 css 수정
  client/src/components/AdminComponents/StoreAlarm/OrderAlram.js
  client/src/components/AdminComponents/TableStatus/TableStatus.js
  client/src/components/Menu/MenuViewList.js
  client/src/components/Preview/HeaderPreview.js
  client/src/components/common/Header.style.js
  client/src/components/home/Footer.js
  client/src/components/usermenu/CartItem.js
  client/src/components/usermenu/Menu.js
  client/src/pages/menu/Cart.js
  client/src/pages/menu/OrderedList.js
  client/src/style/footer.style.js
  client/src/style/index.style.js
  client/src/style/menu.style.js
Labels: 버그, 스타일링

#109 [FE] Modify category, menu, preview error, Add Token
  client/public/favicon.ico
  client/public/favicon_black.ico
  client/src/assets/Group.png
  client/src/components/AdminComponents/TableStatus/TableStatus.js
  client/src/components/Menu/Category/CategoryAdd.js
  client/src/components/Menu/Category/CategoryLi.js
  client/src/components/Menu/MenuList.js
  client/src/components/Preview/BottomNavPreview.js
  client/src/components/Preview/HomePreview.js
  client/src/components/Preview/NavMenuPreview.js
  client/src/components/Preview/PreviewModal.js
  client/src/components/Preview/StorePreview.js
  client/src/components/Preview/menuAppPreview.js
  client/src/components/common/Header.js
  client/src/components/common/Header.style.js
  client/src/components/usermenu/StoreMenuList.js
  client/src/pages/menuAdmin/CategoryMapLi.js
  client/src/pages/menuAdmin/Menu.js
  client/src/pages/menuAdmin/MenuLi.js
  client/src/pages/menuAdmin/SetMenu.js
  client/src/pages/menuAdmin/SetMenu.style.js
  client/src/pages/menuAdmin/SetMenuLi.js
  client/src/redux/reducers/menuSaveItemReducer.js
  client/src/style/menu.style.js
Labels: 버그, 리팩토링, 스타일링

#111 [FE] signup 반응형 스타일, 유효성 수정
  client/src/pages/Signup/MemberInfo.Style.js
  client/src/pages/Signup/MemberInfo.js
  client/src/pages/Signup/SignupTos.Style.js
  client/src/pages/Signup/SignupTos.js
  client/src/pages/Signup/StoreInfo.Style.js
  client/src/pages/Signup/StoreInfo.js
Labels: 리팩토링

#115 [FE] 메타정보 추가 및 css수정
  client/public/index.html
  client/src/assets/image/admin8.png
  client/src/components/AdminComponents/QrTable/QrInfo.js
  client/src/components/AdminComponents/QrTable/QrTable.js
  client/src/components/Preview/StorePreview.js
  client/src/components/home/Section3.js
  client/src/components/home/Slider.js
  client/src/components/usermenu/MenuDetailed.js
Labels: 문서, 스타일링

#118 [FE] Guide Modal 제작
  client/favicon.ico
  client/favicon_black.ico
  client/public/index.html
  client/src/components/common/GuideModal.js
  client/src/pages/Signup/Login.js
  client/src/pages/user/AlarmsPage.js
  client/src/redux/action/action.js
  client/src/redux/reducers/gnbReducer.js
  client/src/redux/reducers/index.js
Labels: 기능

#119 [FE] 주석 삭제
  client/src/pages/Signup/MemberInfo.js
  client/src/pages/Signup/StoreInfo.js
Labels: 리팩토링

#120 🐛 BUG: 주문 알람 삭제 이벤트 버블링 수정/주문 알람 시간 음수면 삭제
  client/src/components/AdminComponents/StoreAlarm/OrderAlram.js
Labels: bug

#123 [FE] 안내 문구, favicon 이미지 추가
  client/favicon.ico
  client/public/android-icon-144x144.png
  client/public/android-icon-192x192.png
  client/public/android-icon-36x36.png
  client/public/android-icon-48x48.png
  client/public/android-icon-72x72.png
  client/public/android-icon-96x96.png
  client/public/apple-icon-114x114.png
  client/public/apple-icon-120x120.png
  client/public/apple-icon-144x144.png
  client/public/apple-icon-152x152.png
  client/public/apple-icon-180x180.png
  client/public/apple-icon-57x57.png
  client/public/apple-icon-60x60.png
  client/public/apple-icon-72x72.png
  client/public/apple-icon-76x76.png
  client/public/apple-icon-precomposed.png
  client/public/apple-icon.png
  client/public/browserconfig.xml
  client/public/favicon-16x16.png
  client/public/favicon-32x32.png
  client/public/favicon-96x96.png
  client/public/index.html
  client/public/manifest.json
  client/public/ms-icon-144x144.png
  client/public/ms-icon-150x150.png
  client/public/ms-icon-310x310.png
  client/public/ms-icon-70x70.png
  client/src/components/Menu/Category/CategoryAdd.js
  client/src/components/Menu/Category/CategoryAlert.js
  client/src/components/Menu/Category/CategoryLi.js
  client/src/components/Menu/Category/CategoryLi.style.js
  client/src/components/Preview/PreviewContent.js
  client/src/components/Preview/StorePreview.js
  client/src/components/Preview/menuAppPreview.js
  client/src/pages/menuAdmin/CategoryMapLi.js
  client/src/pages/menuAdmin/SetMenu.js
  client/src/redux/reducers/menuSaveItemReducer.js
Labels: 리팩토링, 스타일링
